### PR TITLE
Add a config file for project ID + Mask the project ID in benchmarks

### PR DESCRIPTION
**Pull request by GhazalSdn**

### CODE REVIEW

**Comment by engshahrad** [comment]
Reformatted some of the newly changed code with Black. Whenever you add code, please make sure we are still compliant by the formatting. 

@GhazalSdn , the use of `***` for benchmarks is 1) not obvious and 2) not documented for the users. I suggest adding some comment in front of every benchmark line that has `PROJECT_ID = '***'` to tell users what to do. You could say, for instance, `replace *** with your Google Cloud Project ID`

**Comment by engshahrad** [comment]
@GhazalSdn made some fixes. For the url addresses in those yaml files, you have inserted *** in the middle of the url path. Does any of your configurations replace it with user's prjoect id? Or users should do it?

**Comment by GhazalSdn** [comment]
@engshahrad Thanks for the changes. I thought # also works for the comments in .ini files.
No, users need to change that part with their own project-id.

**Comment by engshahrad** [comment]
Thanks. @mohannashahrad we need your help with parametrizing the yaml files for gcp_workflows benchmarks.

**Comment by mohannashahrad** [comment]
@engshahrad The [latest commit](https://github.com/ubc-cirrus-lab/unfaasener/commit/277f46fda8e22483510b9ecc4e8bae8420bfcdbd)  contains the parameterized  yaml files for gcp_workflows benchmarks. I tested all the new updated files in gcp console, and they all ran successfully.

**Comment by engshahrad** [comment]
@mohannashahrad can you add information about filling `GOOGLE_CLOUD_LOCATION` and `GOOGLE_CLOUD_PROJECT_ID` to the [readme](https://github.com/ubc-cirrus-lab/unfaasener/blob/add-configs/benchmarks/README.md) of benchmarks under number 2?

Also, did you test it and are you sure that the yaml parameters work? Testing for at least one benchmark would suffice.

**Comment by mohannashahrad** [comment]
@engshahrad  Sure, I'll add information on those parameters. Indeed there is no need to fill or replace `GOOGLE_CLOUD_LOCATION` and `GOOGLE_CLOUD_PROJECT_ID`. The only thing to note for the end user is that their Google Workflows should be in the same location as their functions for the code to work. I'll add more details into the README shortly. I tested the yaml parameters, and they work as expected.

**Review by engshahrad — APPROVED** [review]

**Pull request merged**
